light_name: light_patchtst_permute



optimizer:
  lr: 0.002
scheduler: none


callbacks:
  monitor: val_loss 
  check_val_every_n_epoch: 1
  max_epochs: 200
  max_steps: -1
  save_top_k: 1
  monitor_mode: min
  patience: 2
  min_delta: 0

dataset:
  batch_size: 256
  num_workers: 4


ssl_loss:
  use_awl_loss: True     # if we use awl loss, lambdas will be ignored.
  use_only_last_layer: False #if True, we only use the patch
  use_consistency_loss: True 
  lambda_consistency: 1.0
  use_margin_loss: True 
  lambda_margin: 1.0