light_name: light_pits_pretrain_mask


optimizer:
  lr: 0.0002
scheduler: 
  scheduler_type: null

callbacks:
  monitor: loss 
  check_val_every_n_epoch: 1
  max_epochs: 10
  max_steps: 4000
  save_top_k: 1
  monitor_mode: min
  patience: 3
  min_delta: 0.0

dataset:
  batch_size: 32
  num_workers: 8
  fast_dev_run: False 
  limit_train_batches: 1.0
  limit_val_batches: 0.0
  train_ratio: 1.0 # This is for SSL setting. Check gilon_dataset.py for example


ssl_loss:
  use_awl_loss: True # If we use AWL loss, lambda_consisntency, lambda_margin will be ignored.
  mask_ratio: 0.4